# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Coding for Refugees
email: 
description: >
  We are giving free programming courses to newly arrived refugees in Sweden.
logo: "/assets/images/logo.jpg"
baseurl: "/codeschool" # the subpath of your site, e.g. /blog
url: "http://alum.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Filip Bonnevier'
bio: >
  Software engineer and technology guy who's trying to help refugees in Sweden.
author_image: "/assets/images/author.jpg"
twitter_username: filipbonnevier
github_username:  alum

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate

exclude: ['vendor']
